#ifndef ACFLASH_COMMON
#define ACFLASH_COMMON

enum {
    ACFLASH_FS_GET_BLOCKSIZE = 0,
    ACFLASH_FS_GET_BLOCKCONT,
    ACFLASH_FS_GET_SIZE_BYTE,
    ACFLASH_FS_REFRESH_FINFO,
    ACFLASH_GET_FLASH_TYPE,
    ACFLASH_FS_GET_BLOCK
};

#endif